# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "bwC3+8Rw1D9HsSc5cznNF2uLqVHggyfbTWhItjKjKDnn49WpCZ45Xg9jyWlyi2nyuxuLQ3Vf+UMpRrPt7TgOZAkGtyLRtOhCm9hvHoSErdd11L6l1jb/DQzz/KPjX6KCJ4zs5dhAyI73p+fdBEhx5MxB+EH7YUEclIMwzPHY2Rfr+8tkmve6K7IgMDCT0LtA6LUxzq86HBbTV0sNScecLnwxdc2h8of60Lcnn0Lbys2saypI05taHhsgQBGkeraiVoRP2JvD3FT4pZl95NbpyAMuaHthfgajtyM5MFd/DPYD3JdpdetVmBV5mr7XcEnELdM1U5Z5fws9o1NbRlh9f0qt0xlXttdzDZ+ePnwBD8MGNuVvnC1vZvS/q4hd3Pkev4+GXJVLdg6N/jp0KaGYeRDZBLLEyxduHG5iX3ySqv1Odkv3jGpwUAtPSsXwnKQrmyksAGp3Azyn+kSjwol4+FwHXNtpn/8ukkxpR26qj1sHlVgHhk+KO2H8RWSnRb8OavboB0PiPyzV7LMcYANnbUn4NzgSUXWVCn6rVqrdfDBlSP88MAJVpIojr0AbIv7rJj6YrweyAyUYSMIXeM8Btjivr8cq6SnsZpO8xQa11obVYaNz/ijTWCN/5WmHTSsDTFYBcuPfNnjw61xc1Ea1ZhBchSxejY2+8hilGX9zjdI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
