travis:
  secure:
    BINSTAR_TOKEN: bwC3+8Rw1D9HsSc5cznNF2uLqVHggyfbTWhItjKjKDnn49WpCZ45Xg9jyWlyi2nyuxuLQ3Vf+UMpRrPt7TgOZAkGtyLRtOhCm9hvHoSErdd11L6l1jb/DQzz/KPjX6KCJ4zs5dhAyI73p+fdBEhx5MxB+EH7YUEclIMwzPHY2Rfr+8tkmve6K7IgMDCT0LtA6LUxzq86HBbTV0sNScecLnwxdc2h8of60Lcnn0Lbys2saypI05taHhsgQBGkeraiVoRP2JvD3FT4pZl95NbpyAMuaHthfgajtyM5MFd/DPYD3JdpdetVmBV5mr7XcEnELdM1U5Z5fws9o1NbRlh9f0qt0xlXttdzDZ+ePnwBD8MGNuVvnC1vZvS/q4hd3Pkev4+GXJVLdg6N/jp0KaGYeRDZBLLEyxduHG5iX3ySqv1Odkv3jGpwUAtPSsXwnKQrmyksAGp3Azyn+kSjwol4+FwHXNtpn/8ukkxpR26qj1sHlVgHhk+KO2H8RWSnRb8OavboB0PiPyzV7LMcYANnbUn4NzgSUXWVCn6rVqrdfDBlSP88MAJVpIojr0AbIv7rJj6YrweyAyUYSMIXeM8Btjivr8cq6SnsZpO8xQa11obVYaNz/ijTWCN/5WmHTSsDTFYBcuPfNnjw61xc1Ea1ZhBchSxejY2+8hilGX9zjdI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
